comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

myblog/urls.py
from django.urls import path

from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView, CategoryView, \
    AddCatView, search

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name="article_detail"),
    path('add_post/', AddPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('cats/<int:pk>', CategoryView.as_view(), name='cats'),
    path('add_cat/', AddCatView.as_view(), name='add_cat'),
    path('search/', search, name='search'),

]

simpleblog/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myblog.urls')),
                  path('', include('comments.urls', namespace='comment')),
                  path('members/', include('django.contrib.auth.urls')),
                  path('members/', include('members.urls')),
                  path('inbox/notifications/',
                       include(notifications.urls, namespace='notifications')),
                  path('notice/', include('notice.urls', namespace='notice')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from myblog.models import Post


class Comment(models.Model):
    commentator = models.ForeignKey(User,
                                    verbose_name='username',
                                    on_delete=models.CASCADE)
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post,
                             verbose_name='post',
                             on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comments'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.commentator, self.text[:20])

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

comments/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from notifications.signals import notify

from myblog.models import Post
from .forms import CommentForm


@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.commentator = request.user
        comment.save()
        messages.add_message(request,
                             messages.SUCCESS,
                             '评论发表成功！',
                             extra_tags='success')
        if request.user != comment.post.author:
            notify.send(
                request.user,
                recipient=comment.post.author,
                verb='评论了你',
                target=comment.post
            )
        return redirect(post)
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request,
                         messages.ERROR,
                         '评论发表失败！请修改表单中的错误后重新提交。',
                         extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

comments/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div>
        <div>
            <label class="form-group" for="{{ form.text.id_for_label }}"></label>
            {{ form.text }}
            {{ form.text.errors }}
        </div>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">发表</button>
</form>

<br>

comments/templates/comments/inclusions/_list.html
{#<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>#}
{#<ul class="comment-list list-unstyled">#}
{#    {% for comment in comment_list %}#}
{#        <li class="comment-item">#}
{#            <span style="color: lightpink"#}
{#                  class="name">{{ comment.commentator.first_name }} {{ comment.commentator.last_name }}</span>#}
{#            <time style="color: green" class="submit-date"#}
{#                  datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>#}
{#            <div class="text">#}
{#                {{ comment.text|linebreaks }}#}
{#            </div>#}
{#        </li>#}
{#    {% empty %}#}
{#        暂无更多评论#}
{#    {% endfor %}#}
{#</ul>#}

<h4>共有{{ comment_count }}条评论</h4>
<div>
    {% for comment in comment_list %}
        <hr>
        <p>
            <strong style="color: pink">
                {{ comment.commentator.first_name }} {{ comment.commentator.last_name }}
            </strong> 于
            <span style="color: green">
                    {{ comment.created_time |date:"Y-m-d H:i:s" }}
                </span> 时说：
        </p>
        <pre style="font-family: inherit; font-size: 1em;">{{ comment.text }}</pre>
    {% empty %}
        暂无更多评论
    {% endfor %}
</div>