myblog/urls.py
from django.urls import path

from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView, CategoryView, \
    AddCatView, search

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name="article_detail"),
    path('add_post/', AddPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('cats/<int:pk>', CategoryView.as_view(), name='cats'),
    path('add_cat/', AddCatView.as_view(), name='add_cat'),
    path('search/', search, name='search'),

]

notice/urls.py
from django.urls import path

from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

simpleblog/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myblog.urls')),
                  path('', include('comments.urls', namespace='comment')),
                  path('members/', include('django.contrib.auth.urls')),
                  path('members/', include('members.urls')),
                  path('inbox/notifications/',
                       include(notifications.urls, namespace='notifications')),
                  path('notice/', include('notice.urls', namespace='notice')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from myblog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView


class CommentNoticeListView(LoginRequiredMixin, ListView):
    context_object_name = 'notices'
    template_name = 'notice/list.html'
    login_url = 'login'

    def get_queryset(self):
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):

    def get(self, request):

        notice_id = request.GET.get('notice_id')

        if notice_id:
            article = Post.objects.get(id=request.GET.get('post_id'))
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect(article)

        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

notice/templates/notice/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    通知
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row mt-4 ml-4">
            <a href="{% url "notice:update" %}" class="btn btn-warning" role="button">清空所有通知</a>
        </div>
        <!-- 未读通知列表 -->
        <div class="row mt-2 ml-4">
            <ul class="list-group">
                {% for notice in notices %}
                    <li class="list-group-item" id="notice_link">
                        <div>
                            {{ notice.actor }}
                            在 <span style=" color: #01a252;" > {{ notice.target }} </span> {{ notice.verb }}。
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                            <script>
                                var t = {{ notice.target }}.
                            </script>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <style>
        #notice_link a:link {
            color: black;
        }

        #notice_link a:visited {
            color: lightgrey;
        }
    </style>
{% endblock content %}