myblog/urls.py
from django.urls import path

from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, LikeView, CategoryView, \
    AddCatView, search

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name="article_detail"),
    path('add_post/', AddPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('cats/<int:pk>', CategoryView.as_view(), name='cats'),
    path('add_cat/', AddCatView.as_view(), name='add_cat'),
    path('search/', search, name='search'),

]

notice/urls.py
from django.urls import path

from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

simpleblog/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myblog.urls')),
                  path('', include('comments.urls', namespace='comment')),
                  path('members/', include('django.contrib.auth.urls')),
                  path('members/', include('members.urls')),
                  path('inbox/notifications/',
                       include(notifications.urls, namespace='notifications')),
                  path('notice/', include('notice.urls', namespace='notice')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from myblog.models import Post


class Comment(models.Model):
    commentator = models.ForeignKey(User,
                                    verbose_name='username',
                                    on_delete=models.CASCADE)
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post,
                             verbose_name='post',
                             on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comments'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.commentator, self.text[:20])

myblog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='static/profile/')
    website_url = models.URLField(max_length=255, blank=True, null=True)
    weibo_url = models.URLField(max_length=255, blank=True, null=True)
    twitter_url = models.URLField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(blank=True, null=True, upload_to='article/%Y%m%d/')
    snippet = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(default=timezone.now)
    modified_date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def total_like(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', args=(str(self.id)))

    def save(self, *args, **kwargs):
        self.modified_date = timezone.now()
        super().save(*args, **kwargs)

myblog/forms.py
from django import forms

from .models import Post,Category

choices = Category.objects.all()

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'snippet', 'category', 'header_image', 'author', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type your title here'}),
            'snippet': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices, attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'xxxa', 'type': 'hidden'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'snippet','category','header_image', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type your title here'}),
            'snippet': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choices, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CatForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type new catgory here'}),
        }

myblog/views.py
import re

import markdown
from django.contrib import messages
from django.db.models import Q
from django.db.models.aggregates import Count
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from markdown.extensions.toc import TocExtension

from .forms import PostForm, EditForm, CatForm
from .models import Post, Category, User


class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-views']

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        category_list = Category.objects.annotate(posts_num=Count('post')).order_by('-posts_num')
        context['category_list'] = category_list
        post_list = Post.objects.all()
        context['post_list'] = post_list
        return context


class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        post.increase_views()
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''
        total_likes = post.total_like()
        total_views = post.views
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True
        else:
            liked = False
        context['total_likes'] = total_likes
        context['liked'] = liked
        context['total_views'] = total_views
        context['body'] = post.body
        context['toc'] = post.toc

        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    success_url = reverse_lazy('home')


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'
    success_url = reverse_lazy('home')


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')


class CategoryView(ListView):
    model = Post
    template_name = 'cats.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class AddCatView(CreateView):
    model = Category
    form_class = CatForm
    template_name = 'add_cat.html'
    success_url = reverse_lazy('home')


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse_lazy('article_detail', args=[str(pk)]))


def search(request):
    q = request.GET.get('q')

    if not q:
        messages.add_message(request, messages.ERROR, "😱，搜索出错惹", extra_tags='danger')
        return redirect('home')
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q) | Q(author__username__icontains=q))
    messages.add_message(request, messages.SUCCESS, "φ(゜▽゜*)♪", extra_tags='success')
    return render(request, 'home.html', {'post_list': post_list})

myblog/templates/add_cat.html
{% extends 'base.html' %}
{% block title %}
    Add category
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <br/>

        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-dark"> Add category!</button>
            </form>
        </div>
    {% else %}
        Piss off
    {% endif %}
{% endblock %}

myblog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}
    Add category
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <br/>

        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-dark"> Add category!</button>
            </form>
        </div>
    {% else %}
        Piss off
    {% endif %}
{% endblock %}

myblog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}
    Make a comment...
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <br/>

        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-dark"> Comment!</button>
            </form>
        </div>
        <script>
            var name = "{{ user.username }}";
            document.getElementById("xxxa").value = name;
        </script>
    {% else %}
        Piss off
    {% endif %}
{% endblock %}

myblog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}
    Create a new post...
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <br/>
        <h1>New post</h1>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {{ form.media }}

                使用markdown功能，请使用source code mode<hr>
                <button class="btn btn-dark"> Post!</button>
            </form>
        </div>
        <script>
            var name = "{{ user.id }}";
            document.getElementById("xxxa").value = name;
        </script>
    {% else %}
        Piss off
    {% endif %}
{% endblock %}

myblog/templates/article_detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% load static %}
{% block title %}
    {{ post.snippet }}
{% endblock %}

<head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <script src="js/jquery-1.11.0.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js"></script>
</head>
{% block content %}

    <body>
    <div class="container">

        <div class="row">
            <div class="col-9">
                <h1>{{ post.title }}<br/></h1>
                <h3><em>{{ post.snippet }}</em></h3>
                <h3><em>Category: {{ post.category.name }}</em></h3>
                <div class="card mb-2">
                    <div class="row g-1">
                        <div class="col-md-4">
                            {% if post.author.profile.profile_pic %}
                                <img src="{{ post.author.profile.profile_pic.url }}" class="rounded-circle">
                            {% else %}
                                <img src="{% static 'myblog/images/default_profile.png' %}" class="rounded-circle"
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.author.first_name }} {{ post.author.last_name }}</h5>
                                <p class="small text-muted">
                                    {% if post.author.profile.id %}
                                        <a href="{% url 'show_profile_page' post.author.profile.id %}">Profile Page</a>
                                    {% endif %}
                                    {% if post.author.profile.website_url %}
                                        | <a href="{{ post.author.profile.website_url }}">Website</a>
                                    {% endif %}
                                    {% if post.author.profile.weibo_url %}
                                        | <a href="{{ post.author.profile.weibo_url }}">Weibo</a>
                                    {% endif %}
                                    {% if post.author.profile.twitter_url %} |
                                        | <a href="{{ post.author.profile.twitter_url }}">Twitter</a>
                                    {% endif %}
                                </p>
                                <p class="card-text">{{ post.author.profile.bio }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    {% if post.header_image %}
                        <img src="{{ post.header_image.url }}" class="img-fluid" style="width: 100%"><br/>
                    {% endif %}
                    <small><b>Posted: {{ post.post_date }} | Likes: {{ total_likes }} |
                        Views: {{ post.views }}</b></small><br/>
                    <div>
                        {% if user.is_authenticated %}
                            {% if user.id == post.author.id %}
                                <a href="{% url 'update_post' post.pk %}">编辑文章</a>
                                <a href="{% url 'delete_post' post.pk %}">删除文章</a>
                            {% endif %}
                            </div>
                        {% endif %}
                </div>
            </div>
                {% if toc %}
                    <div class="col-3 mt-4">
                        <h4 class="widget-title">Menu</h4>
                        {{ toc | safe }}
                    </div>
                {% endif %}
        </div>
    </div>
    <div>
        <br/><br/>

        <div class="container">
            {{ body | safe }}
        </div>
    </div>
    <hr>
    <div>
        <form action="{% url 'like_post' post.pk %}" method="post">
            {% csrf_token %}
            {% if user.is_authenticated %}
                {% if liked %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-danger">Unlike
                    </button>
                {% else %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-dark"> like</button>
                {% endif %}
                <hr>
            {% endif %}
        </form>
    </div>

    <h3>发表评论</h3>
    <div class="comment-list-panel">
        {% if user.is_authenticated %}
            {% show_comment_form post %}
        {% else %}
            <div align="center"><strong>请<a href="{% url 'login' %}">登陆</a>后回复</strong></div>
            <br/><br/><br/>
        {% endif %}
        {% show_comments post %}
        <hr>
    </div>
    <div>
        <a class="btn btn-dark" href="{% url 'home' %}">Back</a>
    </div>

    </body>
{% endblock %}

myblog/templates/base.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!doctype html>
<html lang="en">

<head>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>
        {% block title %}
            Forum
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Forum</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div align="left">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'add_post' %}">Add Post</a>
                        </li>
                        {% if user.is_staff %}
                            <a class="nav-link" href="{% url 'add_cat' %}">Add Cats</a>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Welcome! {{ user.first_name }}{{ user.last_name }}
                                {% if unread_count %}
                                    <svg viewBox="0 0 8 8" width="8px" height="8px">
                                        <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                                    </svg>
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'notice:list' %}">Notifications
                                    {% if unread_count %}
                                        <span class="badge badge-danger">{{ unread_count }}</span>
                                    {% endif %}
                                </a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'edit_profile' %}">Settings</a></li>
                                {% if user.profile.id %}
                                    <li><a class="dropdown-item" href="{% url 'edit_profile_page' user.profile.id %}">Edit
                                        Profile Page</a></li>
                                    <li><a class="dropdown-item"
                                           href="{% url 'show_profile_page' user.profile.id %}">Profile
                                        Page</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'create_profile_page' %}">Create Profile
                                        Page</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
        <form class="d-flex" role="search" method="get" id="searchform" action="{% url 'search' %}">
            <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
{#        <form role="search" method="get" id="searchform" action="{% url 'search' %}">#}
{#            <input type="search" name="q" placeholder="search" required style="width: 20px">#}
{#            <button type="submit" class="btn btn-dark"> Go</button>#}
{#        </form>#}
    </div>
</nav>
<br/>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
-->
</body>

</html>
<footer>
    <div class="container">
        <p align="right" class="copyright">&copy; SPM2021</p>
    </div>
</footer>

myblog/templates/category.html
{% extends 'base.html' %}
{% block content %}
    {% if  category_posts %}
        <h1>{{ cats }}</h1>
        <ul>
            {% for post in category_posts %}
                <li>
                    <small>
                        <a href="{% url 'article_detail' post.pk %}">{{ post.title }}</a>
                        By: {{ post.author.username }} {{ post.post_date }}
                        <a class="button"
                           href="{% url 'category' post.category|slugify %}">{{ post.category.title }}</a>
                        {#                    {% if user.is_authenticated %}#}
                        {#                        {% if user.id == post.author.id %}#}
                        {#                            <a class="button" href="{% url 'update_post' post.pk %}">edit</a>#}
                        {#                            <a class="button" href="{% url 'delete_post' post.pk %}">delete</a>#}
                        {#                        {% endif %}#}
                        {#                    {% endif %}#}
                        <br/>
                        {{ post.title_tag }}
                        <br/>
                    </small>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        Sorry, there's no content under this cate.
    {% endif %}
    <hr>
    <button><a href="{% url 'home' %}"> Back</a></button>
{% endblock %}

myblog/templates/category_list.html
{% extends 'base.html' %}
{% block title %}
    Blog Catgories
{% endblock %}
{% block content %}
    {% for item in cat_menu_list %}
        <h4 align="left"><a class="dropdown-item" href={% url 'category' item %}>{{ item }}</a></h4>
    {% endfor %}

{% endblock %}

myblog/templates/cats.html
{% extends 'base.html' %}
{% block title %}
    {% if post_list %}
    {% else %}
        No Content
    {% endif %}
{% endblock %}
{% block content %}
    {% if post_list %}
        {% for post in post_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title"><a href="{% url 'article_detail' post.pk %}">{{ post.title }}</a></h4>
                    <p class="card-text">{% if post.author.profile.id %}
                        <a href="{% url 'show_profile_page' post.author.profile.id %}">{{ post.author.username }}</a>
                    {% else %}
                        {{ post.author.username }}
                    {% endif %}</p>
                    <p class="card-text">{{ post.snippet }}</p>
                    <p class="card-text"><small class="text-muted">{{ post.modified_date }} 浏览量：{{ post.views }}
                        点赞数：{{ post.total_like }}
                        评论量：{{ post.comment_set.count }}</small></p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>No Content</h1>
    {% endif %}
{% endblock %}

myblog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}
    Delete post...
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <ul align="center">
                <h1>Deleting your post</h1>
                <strong>are you sure ?!</strong>
                <br/><br/><br/>
                <div class="form-group">
                    <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-dark"> Delete!</button>
                    </form>
                </div>
            </ul>
        {% else %}
            Piss off
        {% endif %}
    {% else %}
        Piss off
    {% endif %}
{% endblock %}

myblog/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <body>
    {{ userList }}
    <div class="container">
        <div class="row">
            <div class="col-3">
                <div>
                    {% if category_list %}
                        <h1>Category</h1>
                        <ol class="list-group list-group-numbered">
                            {% for cats in category_list %}
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                    <div class="ms-2 me-auto">
                                        <div class="fw-bold"></div>
                                        <a class="dropdown-item" href="{% url 'cats' cats.pk %}">{{ cats.name }}</a>
                                    </div>
                                    <span class="badge bg-primary rounded-pill">{{ cats.posts_num }}</span>
                                </li>
                            {% endfor %}
                        </ol>
                    {% else %}
                    {% endif %}
                    {% if userList %}
                        {% for user in userList %}
                            {{ user }}
                        {% endfor %}
                    {% else %}
                    {% endif %}
                </div>
            </div>

            {% if category_list %}
                <div class="col-9">
                <h1>Hot Posts💥</h1>
            {% else %}
                {% if post_list %}
                    <div>
                    <h1>Results:</h1>
                {% else %}
                    <h1 align='left'>No Content Found</h1>
                {% endif %}
            {% endif %}
            <div>
                <div>
                    {% for post in post_list %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <a href="{% url 'article_detail' post.pk %}"><h4
                                        class="card-title">{{ post.title }}</h4>
                                </a>

                                <p class="card-text">{% if post.author.profile.id %}
                                    🖊
                                    <a href="{% url 'show_profile_page' post.author.profile.id %}">{{ post.author.username }}</a>
                                {% else %}
                                    {{ post.author.username }}
                                {% endif %}</p>
                                <p class="card-text">{{ post.snippet }}</p>
                                <p class="card-text"><small class="text-muted">updated: {{ post.modified_date }}
                                    👀 {{ post.views }}
                                    👍 {{ post.total_like }}
                                    👄 {{ post.comment_set.count }}</small></p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            </div>
            </div>
        </div>
    </body>
{% endblock %}

myblog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}
    Update a blog post
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <h1>Update a blog post</h1>
            <br/>
            <div class="form-group">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button class="btn btn-dark"> Update!</button>
                </form>
            </div>
        {% else %}
            Piss off
        {% endif %}
    {% else %}
        Piss off
    {% endif %}
{% endblock %}